"""initial config store schema

`zfsbackup/config/store/models.py` is the source of truth for this schema --
`Base.metadata` there, not this file, is what to change first. This
revision is what `alembic revision --autogenerate` produces against an
empty database when compared to that metadata: it creates all six tables
(`datasets`, `destinations`, `global_settings`, `remote_server`,
`dataset_remotes`, `retention_rules`) with every constraint models.py
declares -- both `retention_rules` partial unique indexes scoped to
`dataset_remote_id IS NULL`, the composite FK tying
`(dataset_id, dataset_remote_id)` to `dataset_remotes(dataset_id, id)`, all
four CHECK constraints (both singletons, both retention-positivity checks,
and `ck_global_settings_prune_literal_requires_seconds`), and every
convention-derived name from `NAMING_CONVENTION`. DDL only -- no rows are
seeded here (`GlobalSettings`'s single row is written by item 8's `import`,
not by a migration).

The `upgrade()`/`downgrade()` bodies below are byte-for-byte what
autogenerate produced; do not hand-edit them; regenerate instead if
`models.py` changes. Free to regenerate wholesale until item 8 ships a real
on-disk database -- once a deployed DB has recorded this revision id in its
`alembic_version` table, replacing this file changes what "already at this
revision" means for that DB, so from that point on schema changes must be
new revisions instead.

Revision ID: 2e8aa45e2667
Revises:
Create Date: 2026-09-15 09:12:41.718134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e8aa45e2667'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('recursive', sa.Boolean(), nullable=False),
    sa.Column('frequency_seconds', sa.Float(), nullable=False),
    sa.Column('frequency_literal', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('name', name=op.f('uq_datasets_name'))
    )
    op.create_table('destinations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_destinations'))
    )
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_prefix', sa.String(), nullable=False),
    sa.Column('check_interval_seconds', sa.Float(), nullable=False),
    sa.Column('check_interval_literal', sa.String(), nullable=True),
    sa.Column('prune_interval_seconds', sa.Float(), nullable=True),
    sa.Column('prune_interval_literal', sa.String(), nullable=True),
    sa.Column('api_host', sa.String(), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('client_id_file', sa.String(), nullable=True),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_global_settings_singleton')),
    sa.CheckConstraint('prune_interval_seconds IS NOT NULL OR prune_interval_literal IS NULL', name=op.f('ck_global_settings_prune_literal_requires_seconds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_settings'))
    )
    op.create_table('remote_server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_dataset', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('id = 1', name=op.f('ck_remote_server_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remote_server'))
    )
    op.create_table('dataset_remotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('destination_name', sa.String(), nullable=False),
    sa.Column('frequency_seconds', sa.Float(), nullable=True),
    sa.Column('frequency_literal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_remotes_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_name'], ['destinations.name'], name=op.f('fk_dataset_remotes_destination_name_destinations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_remotes')),
    sa.UniqueConstraint('dataset_id', 'destination_name', name='uq_dataset_remotes_dataset_destination'),
    sa.UniqueConstraint('dataset_id', 'id', name='uq_dataset_remotes_dataset_id_id')
    )
    op.create_table('retention_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_remote_id', sa.Integer(), nullable=True),
    sa.Column('age_seconds', sa.Float(), nullable=False),
    sa.Column('age_literal', sa.String(), nullable=True),
    sa.Column('keep_for_seconds', sa.Float(), nullable=False),
    sa.Column('keep_for_literal', sa.String(), nullable=True),
    sa.CheckConstraint('age_seconds > 0', name=op.f('ck_retention_rules_age_positive')),
    sa.CheckConstraint('keep_for_seconds > 0', name=op.f('ck_retention_rules_keep_for_positive')),
    sa.ForeignKeyConstraint(['dataset_id', 'dataset_remote_id'], ['dataset_remotes.dataset_id', 'dataset_remotes.id'], name='fk_retention_rules_dataset_remote', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_retention_rules_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_rules')),
    sa.UniqueConstraint('dataset_remote_id', 'age_seconds', name='uq_retention_rules_remote_age'),
    sa.UniqueConstraint('dataset_remote_id', 'keep_for_seconds', name='uq_retention_rules_remote_keep_for')
    )
    with op.batch_alter_table('retention_rules', schema=None) as batch_op:
        batch_op.create_index('uq_retention_rules_dataset_age_null_remote', ['dataset_id', 'age_seconds'], unique=True, sqlite_where=sa.text('dataset_remote_id IS NULL'))
        batch_op.create_index('uq_retention_rules_dataset_keep_for_null_remote', ['dataset_id', 'keep_for_seconds'], unique=True, sqlite_where=sa.text('dataset_remote_id IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retention_rules', schema=None) as batch_op:
        batch_op.drop_index('uq_retention_rules_dataset_keep_for_null_remote', sqlite_where=sa.text('dataset_remote_id IS NULL'))
        batch_op.drop_index('uq_retention_rules_dataset_age_null_remote', sqlite_where=sa.text('dataset_remote_id IS NULL'))

    op.drop_table('retention_rules')
    op.drop_table('dataset_remotes')
    op.drop_table('remote_server')
    op.drop_table('global_settings')
    op.drop_table('destinations')
    op.drop_table('datasets')
    # ### end Alembic commands ###
