"""SQLAlchemy 2.0 declarative ORM models for the zfsbackup config store.

Mirrors the dataclass model in `zfsbackup/config.py` as it stands after
items 2b (retention keep_for/age uniqueness), 3b (per-destination retention
overrides), and the item-3 review pass (retention overrides scoped by
`dataset_remote_id` rather than a bare `destination_name`; see below). This
module defines schema only -- see `zfsbackup/store/__init__.py` for why the
ORM layer is kept separate from the `BackupConfig`/`DatasetConfig`
dataclasses. No engine/session code lives here (that is a later item); no
mapper conversion lives here either (also a later item).

Every duration is stored as a `(*_seconds, *_literal)` pair: the seconds
value is what the retention/scheduling algorithms compare and sort on, and
the literal is what makes a YAML round-trip preserve a user's original text
(``"30d"`` rather than rewriting it to the numerically-identical ``"1M"``).
Most `*_literal` columns are nullable: `Duration.literal` is `Optional[str]`
(it is `None` for sub-second values, which have no representable literal in
`config.py`'s grammar -- see `Duration._synthesize`/`.literal`), and a plain
`timedelta` has no `.literal` at all. A NULL `*_literal` means "no literal on
record; re-synthesize a best-effort one from `*_seconds` on read" rather than
an error -- synthesis is deterministic (`Duration._synthesize`), so nothing
is lost, and this is strictly more forgiving than raising for a value the
domain model itself considers legal. (In practice sub-second durations
cannot reach the DB via YAML, since `config.py`'s grammar is integer-only,
but `DatasetConfig.from_property` can decode one from a wire float, so the
model tolerates it here too.)

Retention scope (see item 3's basis, `backup_manager.py`'s
`needs_prunning`): retention is a bijection between intervals (`age`) and
expiries (`keep_for`) *within a scope*, where the scope is either a dataset
(local pruning) or a single per-destination override for that dataset.
`RetentionRule.dataset_remote_id IS NULL` is the dataset-level scope (what a
destination with no override of its own inherits); a non-NULL
`dataset_remote_id` scopes a rule to that `DatasetRemote` row (one dataset,
one destination) exclusively -- see `RetentionRule`'s docstring for why this
replaced a bare `destination_name` column.

SQLite treats NULLs as distinct in ordinary UNIQUE constraints, so a plain
``UNIQUE(dataset_remote_id, age_seconds)`` does not constrain the
dataset-level (NULL) rows at all -- every NULL compares unequal to every
other NULL. The ordinary unique constraint below therefore only constrains
the non-NULL (per-destination) scope; the NULL/dataset-level scope is
constrained separately via partial unique indexes
(`sqlite_where=text("dataset_remote_id IS NULL")`).

`Base.metadata` carries an explicit `naming_convention` so every
*implicitly* named constraint (bare PKs, FKs, and `Dataset.name`'s
column-level `unique=True`) gets a deterministic, introspectable name. This
must be in place before the first Alembic revision is generated: SQLite's
`batch_alter_table` requires naming a constraint to alter it, so an
autogenerated migration built against an unnamed schema would not match a
`create_all()`-built database's (also unnamed, but *differently* unnamed --
SQLAlchemy does not guarantee stable default names) constraints.
"""

from __future__ import annotations

from typing import List, Optional

from sqlalchemy import (
    CheckConstraint,
    ForeignKey,
    ForeignKeyConstraint,
    Index,
    MetaData,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

# Standard SQLAlchemy/Alembic naming convention. Explicitly-named
# constraints/indexes elsewhere in this module keep their own names; this
# only fills in names for constraints SQLAlchemy would otherwise generate
# implicitly (primary keys, foreign keys, and `Dataset.name`'s column-level
# `unique=True`).
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every table in the config store."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class GlobalSettings(Base):
    """Single-row table mirroring `BackupConfig`'s scalar fields.

    Enforced as a singleton via `CHECK (id = 1)` on the primary key: any
    row other than `id = 1` violates the check, and a second `id = 1` row
    violates the primary key. No key/value EAV table is used here -- it
    would defeat typing (see docs/config_db_cli_plan.md item 3).

    Unlike `RemoteServer` (its structural twin below), an absent row here is
    always an error state: `BackupConfig` has no "no global settings"
    representation, so a missing row means an uninitialized or corrupted
    DB, never a deliberate `None`. See `RemoteServer`'s docstring for the
    contrasting case -- two identically-shaped singleton tables with
    opposite "row missing" semantics.
    """

    __tablename__ = "global_settings"
    __table_args__ = (
        # Short suffix, not the full "ck_..." name: the "ck" naming
        # convention's %(constraint_name)s token combines with whatever
        # name is given here, so passing the already-prefixed name would
        # double it up into "ck_global_settings_ck_global_settings_singleton".
        CheckConstraint("id = 1", name="singleton"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, default=1)
    snapshot_prefix: Mapped[str] = mapped_column(default="autosnap")
    check_interval_seconds: Mapped[float] = mapped_column(nullable=False)
    check_interval_literal: Mapped[Optional[str]] = mapped_column(nullable=True)
    prune_interval_seconds: Mapped[float] = mapped_column(nullable=False)
    prune_interval_literal: Mapped[Optional[str]] = mapped_column(nullable=True)
    api_host: Mapped[str] = mapped_column(default="127.0.0.1")
    api_port: Mapped[int] = mapped_column(default=8080)
    dry_run: Mapped[bool] = mapped_column(default=False)
    client_id_file: Mapped[str] = mapped_column(nullable=False)
    # Bumped on every write; used by items 15/17 to detect concurrent
    # modification (read generation, write, compare-and-swap on save).
    generation: Mapped[int] = mapped_column(default=0, nullable=False)

    def __repr__(self) -> str:
        return f"GlobalSettings(snapshot_prefix={self.snapshot_prefix!r}, generation={self.generation})"


class Dataset(Base):
    """One managed dataset, mirroring `DatasetConfig` minus its retention
    rules and per-destination remote config, which live in their own
    tables (`RetentionRule`, `DatasetRemote`) keyed by `dataset_id`.
    """

    __tablename__ = "datasets"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(unique=True, nullable=False)
    recursive: Mapped[bool] = mapped_column(default=False)
    frequency_seconds: Mapped[float] = mapped_column(nullable=False)
    frequency_literal: Mapped[Optional[str]] = mapped_column(nullable=True)
    enabled: Mapped[bool] = mapped_column(default=True)

    # DB already has ON DELETE CASCADE on the children's dataset_id FK, so
    # passive_deletes=True is paired with cascade="all, delete-orphan" to
    # let SQLAlchemy skip loading the children before delete and rely on the
    # DB to do the cascading. This is the correct pairing throughout this
    # module: cascade="all, delete-orphan" for genuinely dataset-owned rows
    # (deleting the row here should always delete them), passive_deletes
    # (True or "all", see below) so the DB's own FK behaviour -- not a
    # session-level SELECT+UPDATE/DELETE -- is what actually happens.
    retention_rules: Mapped[List["RetentionRule"]] = relationship(
        back_populates="dataset",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )
    remotes: Mapped[List["DatasetRemote"]] = relationship(
        back_populates="dataset",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return f"Dataset(name={self.name!r})"


class Destination(Base):
    """A remote server that accepts backup streams, mirroring `Destination`
    (`config.py`). Keyed by name rather than a surrogate id: destination
    names are the natural key used throughout the config (dataset `remote`
    entries, `RemoteDatasetConfig.destination`, `to_property(destination)`)
    and there is no reason to invent a second identifier for them.

    Deliberately has no relationship to `RetentionRule`: per-destination
    retention overrides are scoped via `RetentionRule.dataset_remote_id`
    (see that class's docstring), so a `Destination` never owns retention
    rows directly -- it can only be reached from one via the owning
    `DatasetRemote`. Traversing from `Destination` straight to its
    "scoped" rules was exactly the item-3-review finding-1 bug (deleting a
    `Destination` after loading `dest.retention_rules` UPDATEd the orphaned
    rules' scope column to NULL -- silently promoting per-destination
    overrides to dataset-level rules instead of removing them); removing
    the relationship makes that mistake structurally unavailable rather
    than relying on remembering not to add a cascade to it.
    """

    __tablename__ = "destinations"

    name: Mapped[str] = mapped_column(primary_key=True)
    url: Mapped[str] = mapped_column(nullable=False)

    # No ON DELETE clause on dataset_remotes.destination_name (see
    # DatasetRemote) -- a destination still referenced by a dataset's
    # remote config must not vanish out from under it. passive_deletes="all"
    # (rather than plain passive_deletes=True, which only suppresses the
    # load of *unloaded* collections and would still null out any
    # already-loaded children) makes that guard explicit: the ORM never
    # touches dataset_remotes rows on a Destination delete, in any case, so
    # the DELETE always reaches the DB and the DB's default FK behaviour
    # (RESTRICT) is what actually raises -- a real
    # "FOREIGN KEY constraint failed", not a misleading
    # "NOT NULL constraint failed" from the ORM's default null-out cascade
    # racing the FK check. Deliberate, not a side effect of omitting
    # `cascade`/`passive_deletes` -- see item-3-review finding 4.
    dataset_remotes: Mapped[List["DatasetRemote"]] = relationship(
        back_populates="destination",
        passive_deletes="all",
    )

    def __repr__(self) -> str:
        return f"Destination(name={self.name!r})"


class DatasetRemote(Base):
    """Per-destination remote backup config for one dataset, mirroring
    `RemoteDatasetConfig`. A NULL `frequency_*` pair means "inherit the
    dataset's own frequency" (`config.py`'s `RemoteDatasetConfig.frequency
    = None` precedent); a NULL `frequency_literal` alone (non-NULL
    `frequency_seconds`) means the sub-second "re-synthesize on read" case
    described in the module docstring -- the two NULL cases are
    distinguished by whether `frequency_seconds` is also NULL.

    `(dataset_id, destination_name)` is unique: `effective_retention_rules`
    and `RemoteBackupManager` both resolve a destination by first match, so
    a second row for the same pair would be silently-dead config rather
    than a rejected duplicate (item-3-review finding 3).

    `(dataset_id, id)` is also declared unique (trivially true, since `id`
    alone is already unique) purely so `RetentionRule` can FK to it as a
    composite parent key -- see that class's docstring for why.

    Per-destination *retention* overrides are not stored here -- they are
    `RetentionRule` rows scoped by `dataset_remote_id`, keeping both axes
    (dataset-level and per-destination) in the one retention table rather
    than duplicating the shape.
    """

    __tablename__ = "dataset_remotes"
    __table_args__ = (
        UniqueConstraint(
            "dataset_id", "destination_name",
            name="uq_dataset_remotes_dataset_destination",
        ),
        # Composite-FK support constraint for RetentionRule -- see that
        # class's docstring. Not a functional dedup: id is already unique.
        UniqueConstraint(
            "dataset_id", "id",
            name="uq_dataset_remotes_dataset_id_id",
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    dataset_id: Mapped[int] = mapped_column(
        ForeignKey("datasets.id", ondelete="CASCADE"), nullable=False
    )
    # No ON DELETE CASCADE here (unlike retention_rules): a destination that
    # is still referenced by a dataset's remote config must be removed from
    # that config explicitly rather than have the reference silently
    # disappear out from under it. See Destination.dataset_remotes for the
    # explicit passive_deletes="all" that makes the DB's resulting RESTRICT
    # behaviour surface as the real error rather than an ORM null-out.
    destination_name: Mapped[str] = mapped_column(
        ForeignKey("destinations.name"), nullable=False
    )
    frequency_seconds: Mapped[Optional[float]] = mapped_column(nullable=True)
    frequency_literal: Mapped[Optional[str]] = mapped_column(nullable=True)

    dataset: Mapped["Dataset"] = relationship(back_populates="remotes")
    destination: Mapped["Destination"] = relationship(back_populates="dataset_remotes")
    # RetentionRule.dataset_remote_id has ON DELETE CASCADE (via the
    # composite FK -- see RetentionRule), so this follows the same
    # cascade="all, delete-orphan" + passive_deletes=True pairing as
    # Dataset's collections: deleting a DatasetRemote always takes its
    # scoped overrides with it, and the DB does the actual cascading.
    #
    # primaryjoin is narrowed to dataset_remote_id == id only (rather than
    # letting SQLAlchemy infer it from the full composite FK, which also
    # touches dataset_id): dataset_id is already written by the
    # RetentionRule.dataset / Dataset.retention_rules relationship, and
    # letting two relationships both claim to synchronize it produces an
    # "overlapping relationship" warning. The DB-level composite FK (not
    # this relationship) is what actually enforces and cascades on
    # dataset_id -- this join is purely for ORM navigation.
    retention_rules: Mapped[List["RetentionRule"]] = relationship(
        back_populates="dataset_remote",
        primaryjoin="DatasetRemote.id == RetentionRule.dataset_remote_id",
        cascade="all, delete-orphan",
        passive_deletes=True,
    )

    def __repr__(self) -> str:
        return f"DatasetRemote(dataset_id={self.dataset_id}, destination_name={self.destination_name!r})"


class RetentionRule(Base):
    """One retention tier, mirroring `RetentionRule` (`config.py`), scoped
    to either a dataset (`dataset_remote_id IS NULL`, local pruning) or a
    single `DatasetRemote` row (`dataset_remote_id` set, a per-destination
    override for that one dataset+destination pairing -- see item 3b).

    Scoped by `dataset_remote_id` rather than a bare `destination_name`
    (item-3-review finding 2): a `destination_name` column FKing straight
    to `destinations.name` let an override exist with no owning
    `DatasetRemote` row at all -- a state `BackupConfig` cannot represent,
    and one where deleting a `DatasetRemote` left its scoped rules behind
    to reappear if the remote was re-added. Scoping through the
    `DatasetRemote` row instead makes an orphan override structurally
    impossible and makes remote deletion cascade correctly.

    `dataset_id` is kept as its own NOT NULL column (rather than derived
    from `dataset_remote_id`) because it must be populated for dataset-level
    rows, which have no `DatasetRemote` to derive it from. For scoped rows
    it is redundant with `dataset_remote_id`'s own dataset -- but rather
    than leave that redundancy unchecked, the composite
    `fk_retention_rules_dataset_remote` FK below ties both columns together
    against `dataset_remotes(dataset_id, id)`: SQLite does not enforce a
    multi-column FK when any of its columns is NULL ("MATCH SIMPLE"), so
    this FK is silently inert for dataset-level rows (`dataset_remote_id`
    NULL) and only engages for scoped rows, where it rejects a `dataset_id`
    that disagrees with the `DatasetRemote` row's actual dataset --
    verified directly (see the item-3-review verification notes) rather
    than assumed. It also supplies `ON DELETE CASCADE`, so a plain
    single-column FK on `dataset_remote_id` alone is unnecessary.

    Both `age` and `keep_for` are unique within a scope -- see the module
    docstring for why, and for the NULL-handling trap that requires the
    partial unique indexes below in addition to the ordinary unique
    constraints.
    """

    __tablename__ = "retention_rules"
    __table_args__ = (
        # Short suffixes -- see GlobalSettings' CheckConstraint for why.
        CheckConstraint("age_seconds > 0", name="age_positive"),
        CheckConstraint("keep_for_seconds > 0", name="keep_for_positive"),
        # Ties (dataset_id, dataset_remote_id) to the owning DatasetRemote
        # row's own (dataset_id, id) -- see the class docstring. Inert for
        # dataset-level rows (dataset_remote_id IS NULL); ON DELETE CASCADE
        # here is what cascades a DatasetRemote delete to its scoped rules.
        ForeignKeyConstraint(
            ["dataset_id", "dataset_remote_id"],
            ["dataset_remotes.dataset_id", "dataset_remotes.id"],
            ondelete="CASCADE",
            name="fk_retention_rules_dataset_remote",
        ),
        # Constrains the non-NULL (per-destination) scope only -- SQLite
        # treats every NULL dataset_remote_id as distinct from every other,
        # so these do NOT constrain dataset-level (NULL) rows. See the
        # partial indexes below for that case. dataset_id is intentionally
        # omitted here: a non-NULL dataset_remote_id already identifies a
        # single (dataset, destination) pairing on its own (and the FK
        # above guarantees dataset_id agrees with it), so including it
        # would be redundant.
        UniqueConstraint(
            "dataset_remote_id", "age_seconds",
            name="uq_retention_rules_remote_age",
        ),
        UniqueConstraint(
            "dataset_remote_id", "keep_for_seconds",
            name="uq_retention_rules_remote_keep_for",
        ),
        # Dataset-level (dataset_remote_id IS NULL) scope: one rule per age,
        # one rule per keep_for. Required in addition to the constraints
        # above -- see the module docstring.
        Index(
            "uq_retention_rules_dataset_age_null_remote",
            "dataset_id", "age_seconds",
            unique=True,
            sqlite_where=text("dataset_remote_id IS NULL"),
        ),
        Index(
            "uq_retention_rules_dataset_keep_for_null_remote",
            "dataset_id", "keep_for_seconds",
            unique=True,
            sqlite_where=text("dataset_remote_id IS NULL"),
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    # Plain FK to datasets.id (independent of the composite FK to
    # dataset_remotes below, which targets a different table and is only
    # engaged for scoped rows) -- always required, including for
    # dataset-level rows.
    dataset_id: Mapped[int] = mapped_column(
        ForeignKey("datasets.id", ondelete="CASCADE"), nullable=False
    )
    # NULL = dataset-level scope. Non-NULL, together with dataset_id,
    # satisfies the composite FK in __table_args__ above.
    dataset_remote_id: Mapped[Optional[int]] = mapped_column(nullable=True)
    age_seconds: Mapped[float] = mapped_column(nullable=False)
    age_literal: Mapped[Optional[str]] = mapped_column(nullable=True)
    keep_for_seconds: Mapped[float] = mapped_column(nullable=False)
    keep_for_literal: Mapped[Optional[str]] = mapped_column(nullable=True)

    dataset: Mapped["Dataset"] = relationship(back_populates="retention_rules")
    # Narrowed primaryjoin -- see DatasetRemote.retention_rules for why
    # dataset_id is deliberately left out of this relationship's join
    # condition even though it is part of the DB-level composite FK.
    dataset_remote: Mapped[Optional["DatasetRemote"]] = relationship(
        back_populates="retention_rules",
        primaryjoin="RetentionRule.dataset_remote_id == DatasetRemote.id",
    )

    def __repr__(self) -> str:
        return (
            f"RetentionRule(dataset_id={self.dataset_id}, "
            f"dataset_remote_id={self.dataset_remote_id!r}, "
            f"age_literal={self.age_literal!r}, keep_for_literal={self.keep_for_literal!r})"
        )


class RemoteServer(Base):
    """Single-row table mirroring `RemoteServerConfig` -- this daemon's
    own server-side config for accepting incoming backup streams. Singleton
    enforced the same way as `GlobalSettings`.

    Unlike `GlobalSettings` (its structural twin above), an absent row here
    is *meaningful*, not an error: it is the correct encoding of
    `BackupConfig.remote_backup = None` (a daemon that does not accept
    incoming backups at all). Two identically-shaped singleton tables with
    opposite "row missing" semantics is easy to get wrong in a mapper (item
    4) that treats "no row" as uniformly "uninitialized" -- it must special-
    case this table, not `GlobalSettings`.
    """

    __tablename__ = "remote_server"
    __table_args__ = (
        CheckConstraint("id = 1", name="singleton"),
    )

    id: Mapped[int] = mapped_column(primary_key=True, default=1)
    target_dataset: Mapped[str] = mapped_column(nullable=False)
    enabled: Mapped[bool] = mapped_column(default=True)

    def __repr__(self) -> str:
        return f"RemoteServer(target_dataset={self.target_dataset!r}, enabled={self.enabled})"
